
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'a b c d S : a S d\n\t\t| A\n\t\t| B  A : A d\n\t\t| C  B : a B c\n\t\t| a B\n\t\t| C  C : b C c\n\t\t| b C\n\t\t| empty empty :'
    
_lr_action_items = {'a':([0,2,],[2,2,]),'b':([0,2,6,],[6,6,6,]),'d':([0,2,3,5,6,7,8,9,10,11,12,13,14,15,],[-12,-12,11,-5,-12,-11,13,-3,-5,-4,-10,-1,-6,-9,]),'$end':([0,1,2,3,4,5,6,7,9,10,11,12,13,14,15,],[-12,0,-12,-2,-3,-5,-12,-11,-7,-8,-4,-10,-1,-6,-9,]),'c':([2,6,7,9,10,12,14,15,],[-12,-12,-11,14,-8,15,-6,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'S':([0,2,],[1,8,]),'A':([0,2,],[3,3,]),'B':([0,2,],[4,9,]),'C':([0,2,6,],[5,10,12,]),'empty':([0,2,6,],[7,7,7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> a S d','S',3,'p_S','ejercicio2.py',15),
  ('S -> A','S',1,'p_S','ejercicio2.py',16),
  ('S -> B','S',1,'p_S','ejercicio2.py',17),
  ('A -> A d','A',2,'p_A','ejercicio2.py',21),
  ('A -> C','A',1,'p_A','ejercicio2.py',22),
  ('B -> a B c','B',3,'p_B','ejercicio2.py',26),
  ('B -> a B','B',2,'p_B','ejercicio2.py',27),
  ('B -> C','B',1,'p_B','ejercicio2.py',28),
  ('C -> b C c','C',3,'p_C','ejercicio2.py',30),
  ('C -> b C','C',2,'p_C','ejercicio2.py',31),
  ('C -> empty','C',1,'p_C','ejercicio2.py',32),
  ('empty -> <empty>','empty',0,'p_empty','ejercicio2.py',37),
]
